# Generated by Django 3.2.5 on 2021-08-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Country Code')),
                ('sovereignty', models.CharField(max_length=100)),
                ('geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='DACMemberCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, null=True, verbose_name='Year')),
                ('provider_type', models.CharField(blank=True, max_length=200, verbose_name='Provider Type')),
                ('provider', models.CharField(max_length=200, verbose_name='Provider')),
                ('provider_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Provider Code')),
                ('adaptation_objective', models.CharField(blank=True, max_length=200, verbose_name='Adaptation Objective (applies to Rio-marked data only)')),
                ('mitigation_objective', models.CharField(blank=True, max_length=200, verbose_name='Mitigation Objective')),
                ('adaptation_dev_finance_commitment_2019', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Adaptation-related Development Finance Commitment (2019)')),
                ('adaptation_dev_finance_commitment_current', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Adaptation-related Development Finance Commitment (current)')),
                ('mitigation_dev_finance_commitment_2019', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Mitigation-related Development Finance Commitment (2019)')),
                ('mitigation_dev_finance_commitment_current', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Mitigation-related Development Finance Commitment (current)')),
                ('overlap_commitment_2019', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Overlap Commitment (2019)')),
                ('overlap_commitment_current', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Overlap Commitment (current)')),
                ('climate_dev_finance_commitment_2019', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Climate-related Development Finance Commitment (2019)')),
                ('climate_dev_finance_commitment_current', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Climate-related Development Finance Commitment (current)')),
                ('channel_delivery_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Channel of Delivery Code')),
                ('channel_delivery', models.CharField(blank=True, max_length=200, verbose_name='Channel of Delivery')),
                ('purpose_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Purpose Code')),
                ('sector', models.CharField(blank=True, max_length=200, verbose_name='Sector (detailed)')),
                ('sub_sector', models.CharField(blank=True, max_length=200, verbose_name='Sub-sector')),
                ('development_cooperation_modality', models.CharField(blank=True, max_length=200, verbose_name='Development of Cooperation Modality')),
                ('financial_instrument', models.CharField(blank=True, max_length=200, verbose_name='Financial Instrument')),
                ('finance_type', models.IntegerField(blank=True, default=0, null=True, verbose_name='Type of Finance')),
                ('gender', models.CharField(blank=True, max_length=200, verbose_name='Gender')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='climate_app.initialmodel')),
            ],
            options={
                'verbose_name': 'DACMemberCountry',
                'verbose_name_plural': 'DACMemberCountries',
            },
        ),
    ]
