# Generated by Django 3.2.5 on 2021-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dacmembercountry",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Publish"),
        ),
    ]
